# Generated by Django 5.1.6 on 2025-09-15 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Category/', verbose_name='Изображение')),
                ('name', models.TextField(verbose_name='Название')),
                ('name_uz', models.TextField(null=True, verbose_name='Название')),
                ('name_ru', models.TextField(null=True, verbose_name='Название')),
                ('name_en', models.TextField(null=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='News/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовка')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='Заголовка')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='Заголовка')),
                ('title_en', models.CharField(max_length=256, null=True, verbose_name='Заголовка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('content', models.TextField(verbose_name='Контент')),
                ('content_uz', models.TextField(null=True, verbose_name='Контент')),
                ('content_ru', models.TextField(null=True, verbose_name='Контент')),
                ('content_en', models.TextField(null=True, verbose_name='Контент')),
                ('is_published', models.CharField(choices=[('True', 'Да'), ('False', 'Нет')], default='False', max_length=5, verbose_name='Опубликовано')),
                ('views', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unfoldapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'News',
            },
        ),
    ]
