# Generated by Django 5.1.6 on 2025-09-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfoldapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.CharField(choices=[('True', 'Да'), ('False', 'Нет')], default='False', max_length=5, verbose_name='Опубликовано'),
        ),
    ]
