# Generated by Django 5.1.6 on 2025-09-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unfoldapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
    ]
