# Generated by Django 5.1.6 on 2025-09-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfoldapp', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='Category/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='News/', verbose_name='Изображение'),
        ),
    ]
